on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: number

jobs:
  build:
    runs-on: [ self-hosted, macOS, android ]
    env:
      date-time: $(date +'%Y%m%dT%H%M%S')
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :app:assembleQaDebug
    - name: Push to S3
      uses: PROTOTYPE/cicd-actions/.github/actions/s3-upload@v1
      with:
        filePath: $GITHUB_WORKSPACE/app/build/outputs/apk/qa/debug/
        s3-url: usa-qa-automate-test
        s3-prefix: valkyrie
        packageKey: android/${{ env.date-time }}
