on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: number
      deploy-env:
        required: false
        type: string
      target:
        required: false
        type: string

jobs:
  build:
    runs-on: [ self-hosted, macOS, android ]
    environment:
      name: ${{ inputs.deploy-env }}
    env:
      gradle-cmd: ${{ vars.GRADLEW_CMD }}
      JAVA_HOME: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
      JAVA_HOME_17_X64: /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
      DEFAULT_ENVIRONMENT: ${{ vars.DEFAULT_ENVIRONMENT }}
      KEY_STORE_PROPERTIES_FILE: ${{ vars.KEY_STORE_PROPERTIES_FILE }}
    steps:
    - uses: actions/checkout@v3
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    - name: Build with Gradle
      run: ./gradlew ${{ inputs.target }}
      shell: bash
    - name: Push to S3
      uses: liberty-group-tech/cicd-actions/.github/actions/s3-upload@master
      with:
        filePath: ${{ github.workspace }}/app/build/outputs/apk/
        s3-url: liberty-dev-app-package
        s3-prefix: liberty
        packageKey: android/${{ github.sha }}-${{ github.run_number }}
        rootUrl: https://apppackage.dev-wellowallet.com
        need-change-profile: true
