on:
  workflow_call:
    inputs:
      deploy-env:
        required: false
        type: string
jobs:
  get-config:
    runs-on: self-hosted
    environment:
      name: ${{ inputs.deploy-env }}
    steps:
      - run: |
          echo Config of environment:
          echo AWS REGION: 
          echo ${{ secrets.AWS_REGION }} | sed 's/./&/g'
          echo AWS ROLE: 
          echo ${{ secrets.AWS_ROLE }} | sed 's/./&/g'
          echo ECS CLUSTER: 
          echo ${{ secrets.ECS_CLUSTER }} | sed 's/./&/g'
          echo TARGET GROUP ARN: 
          echo ${{ secrets.TARGETGROUPARN }} | sed 's/./&/g'
          echo SECURITY GROUPS: 
          echo ${{ secrets.SECURITYGROUPS }} | sed 's/./&/g'
          echo SUBNETS: 
          echo ${{ secrets.SUBNETS }} | sed 's/./&/g'
          echo TASK DEF FILE: 
          echo ${{ secrets.TASK_DEF_FILE }} | sed 's/./&/g'
          echo DOCKER REGISTRY: 
          echo ${{ secrets.DOCKER_REGISTRY }} | sed 's/./&/g'
          echo LOAD BALANCERS: 
          echo ${{ secrets.LB_JSON }} | sed 's/./&/g'
        shell: bash
