on:
  workflow_call:
    inputs:
      deploy-env:
        required: false
        type: string
jobs:
  get-config:
    runs-on: self-hosted
    environment:
      name: ${{ inputs.deploy-env }}
    steps:
      - run: |
          echo Config of environment:
          echo AWS REGION: ${{ secrets.AWS_REGION }}
          echo AWS ROLE: ${{ secrets.AWS_ROLE }}
          echo ECS CLUSTER: ${{ secrets.ECS_CLUSTER }}
          echo TARGET GROUP ARN: ${{ secrets.TARGETGROUPARN }}
          echo SECURITY GROUPS :${{ secrets.SECURITYGROUPS }}
          echo SUBNETS: ${{ secrets.SUBNETS }}
          echo TASK DEF FILE: ${{ secrets.TASK_DEF_FILE }}
          echo DOCKER REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          echo LOAD BALANCERS: ${{ secrets.LB_JSON }} | 
          sed 's/./& /g'
        shell: bash
