on:
  workflow_call:
    inputs:
      service-config-name:
        required: true
        type: string
      go-version:
        required: false
        type: number
      containerName:
        required: false
        type: string
      containerPort:
        required: false
        type: string
      ecs-service:
        required: false
        type: string
      deploy-env:
        required: false
        type: string
jobs:
  ci:
    runs-on: self-hosted
    environment:
      name: ${{ inputs.deploy-env }}
    env:
      aws-region: ${{ secrets.AWS_REGION }}
      aws-role: ${{ secrets.AWS_ROLE }}
      cluster: ${{ secrets.ECS_CLUSTER }}
      targetGroupArn: ${{ secrets.TARGETGROUPARN }}
      securityGroups: ${{ secrets.SECURITYGROUPS }}
      subnets: ${{ secrets.SUBNETS }}
      task-definition-file: ${{ secrets.TASK_DEF_FILE }}
      aws-registry: ${{ secrets.DOCKER_REGISTRY }}
    name: CICD flow of java gradle build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - run: make
        shell: bash
