on:
  workflow_call:
    inputs:
      deploy-env:
        required: false
        type: string
      target:
        required: false
        type: string

jobs:
  build:
    runs-on: macos-latest
    environment:
      name: ${{ inputs.deploy-env }}
    env:
      exec-cmd: ${{ vars.EXEC_CMD }}
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.5'
        bundler-cache: true
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.1.0'
    - uses: actions/cache@v3
      with:
       path: Pods
       key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
       restore-keys: |
         ${{ runner.os }}-pods-
    - name: Bundle Install
      run: bundle install
      shell: zsh {0}
    - name: Bundle EXEC Fastlane
      run: bundle exec fastlane ${{ inputs.target }} --verbose
      shell: zsh {0}
    - name: Push to artifact
      uses: actions/upload-artifact@v4
      with:
        name: wello-dev-ipa
        path: ${{ github.workspace }}/build/
