on:
  workflow_call:
    inputs:
      deploy-env:
        required: false
        type: string
      target:
        required: false
        type: string

jobs:
  build:
    runs-on: [ self-hosted, macOS, ios ]
    environment:
      name: ${{ inputs.deploy-env }}
    env:
      exec-cmd: ${{ vars.EXEC_CMD }}
    steps:
    - uses: actions/checkout@v3
    - name: Bundle Install
      run: bundle install
      shell: zsh {0}
    - name: Bundle EXEC Fastlane
      run: bundle exec fastlane ${{ inputs.target }}
      shell: zsh {0}
    - name: Change local profile
      run: |
        export AWS_PROFILE=new-pack
      shell: bash
    - name: Push to S3
      uses: liberty-group-tech/cicd-actions/.github/actions/s3-upload@master
      with:
        filePath: ${{ github.workspace }}/build/
        s3-url: liberty-dev-app-package
        s3-prefix: liberty
        packageKey: ios/${{ github.sha }}-${{ github.run_number }}
        rootUrl: https://apppackage.dev-wellowallet.com
