on:
  workflow_call:
    inputs:
      jar-path:
        required: true
        type: string
      java-version:
        required: false
        type: number
      containerName:
        required: false
        type: number
      containerPort:
        required: false
        type: number
      targetGroupArn:
        required: false
        type: number
      securityGroups:
        required: true
        type: string
      subnets:
        required: true
        type: string
jobs:
  ci:
    runs-on: self-hosted
    name: CICD flow of java gradle build
    steps:
      - uses: PROTOTYPE/cicd-actions/.github/actions/ci-java-gradle-action@v1
        with:
          java-version: ${{ inputs.java-version }}
          jar-path: ${{ inputs.jar-path }}
      - name: Deploy Amazon ECS task definition
        uses: PROTOTYPE/cicd-actions/.github/actions/ecs-deploy@v1
        with:
          service: happytree-demo
          cluster: usa-tools-cluster
          containerName: ${{ inputs.containerName }}
          containerPort: ${{ inputs.containerPort }}
          targetGroupArn: ${{ inputs.targetGroupArn }}
          securityGroups: ${{ inputs.securityGroups }}
          subnets: ${{ inputs.subnets }}
          wait: true
