on:
  workflow_call:
    inputs:
      jar-path:
        required: true
        type: string
      java-version:
        required: true
        type: number
      project-name:
        required: false
        type: string
        default: 123
  
jobs:
  ci_build:
    runs-on: self-hosted
    name: CI flow of java gradle build
    steps:
      - name: Echo default
        run: echo "${{ inputs.project-name }} is a project name"
      - name: Code CI build
        uses: PROTOTYPE/cicd-actions/.github/actions/ci-java-gradle-action@v1
        with:
          java-version: ${{ inputs.java-version }}
          jar-path: ${{ inputs.jar-path }}
