on:
  workflow_call:
    inputs:
      jar-path:
        required: true
        type: string
      java-version:
        default: 11
        required: false
        type: number

jobs:
  ci_build:
    runs-on: self-hosted
    name: CI flow of java gradle build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ github.event.inputs.java-version }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          gradle-version: release-candidate
          build-root-directory: ${{ github.event.inputs.jar-path }}
