on:
  workflow_call:
    inputs:
      jar-path:
        required: true
        type: string
      java-version:
        default: 11
        required: false
        type: number

jobs:
  ci_build:
    runs-on: self-hosted
    name: CI flow of java gradle build
    steps:
      - run: echo "CICD process is not ready yet, please wait"
        shell: bash
