on:
  workflow_call:
    inputs:
      jar-path:
        required: true
        type: string
      java-version:
        default: 11
        required: false
        type: number

jobs:
  ci:
    runs-on: self-hosted
    name: CICD flow of java gradle build
    steps:
      - uses: PROTOTYPE/cicd-actions/.github/actions/ci-java-gradle-action@v1
        with:
          java-version: ${{ inputs.java-version }}
          jar-path: ${{ inputs.jar-path }}
      - run: echo "CD process is not ready yet, please wait"
        shell: bash
