on:
  workflow_call:
    inputs:
      jar-path:
        required: true
        type: string
      java-version:
        required: true
        type: number

jobs:
  ci_build:
    runs-on: self-hosted
    name: CI flow of java gradle build
    steps:
      - name: Code CI build
        uses: PROTOTYPE/cicd-actions/.github/actions/ci-java-gradle-action@v1
        with:
          java-version: ${{ inputs.java-version }}
          jar-path: ${{ inputs.jar-path }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Docker build and push to local registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: 333501191747.dkr.ecr.us-east-1.amazonaws.com/test-cicd-proj:latest
