on:
  workflow_call:
    inputs:
      jar-path:
        required: true
        type: string
      java-version:
        default: 11
        required: false
        type: number

jobs:
  ci:
    uses: PROTOTYPE/cicd-flows/.github/workflows/java-gradle-ci.yml@master
    with:
      jar-path: ${{ inputs.jar-path }}
      java-version: ${{ inputs.java-version }}
  cd:
    runs-on: self-hosted
    name: CI flow of java gradle build
    steps:
      - run: echo "CD process is not ready yet, please wait"
        shell: bash
