on:
  workflow_call:
    inputs:
      service-config-name:
        required: true
        type: string
      jar-path:
        required: true
        type: string
      java-version:
        required: false
        type: number
      containerName:
        required: false
        type: string
      containerPort:
        required: false
        type: string
      ecs-service:
        required: false
        type: string
      deploy-env:
        required: false
        type: string
jobs:
  ci:
    runs-on: self-hosted
    environment:
      name: ${{ inputs.deploy-env }}
    env:
      aws-region: ${{ secrets.AWS_REGION }}
      aws-role: ${{ secrets.AWS_ROLE }}
      cluster: ${{ secrets.ECS_CLUSTER }}
      targetGroupArn: ${{ secrets.TARGETGROUPARN }}
      securityGroups: ${{ secrets.SECURITYGROUPS }}
      subnets: ${{ secrets.SUBNETS }}
      task-definition-file: ${{ secrets.TASK_DEF_FILE }}
      aws-registry: ${{ secrets.DOCKER_REGISTRY }}
    name: CICD flow of java gradle build
    steps:
      - run: echo ${{ env.aws-region }}-${{ env.cluster }}-${{ env.targetGroupArn }}-${{ env.securityGroups }}-${{ env.subnets }}-${{ env.aws-role }}-${{ env.task-definition-file }}
        shell: bash
      - name: Code CI build
        uses: PROTOTYPE/cicd-actions/.github/actions/ci-java-gradle-action@v1
        with:
          java-version: ${{ inputs.java-version }}
          jar-path: ${{ inputs.jar-path }}
      - name: Init Config
        uses: PROTOTYPE/cicd-actions/.github/actions/get-config@master
        with:
          service-config-name: ${{ inputs.service-config-name }}
      - name: Docker build and push
        id: docker-build
        uses: PROTOTYPE/cicd-actions/.github/actions/ecr-build-push@v1
        with:
          aws-region: ${{ env.aws-region }}
          aws-role: ${{ env.aws-role }}
          project-name: ${{ inputs.containerName }}
          aws-registry: ${{ env.aws-registry }}
      - run: echo ${{ steps.docker-build.outputs.image-name }}
        shell: bash
      - name: Deploy Amazon ECS task definition
        uses: PROTOTYPE/cicd-actions/.github/actions/ecs-deploy@v1
        timeout-minutes: 5
        with:
          aws-region: ${{ env.aws-region }}
          aws-role: ${{ env.aws-role }}
          ecs-service: ${{ inputs.ecs-service }}
          ecs-cluster: ${{ env.cluster }}
          image-full-name: ${{ steps.docker-build.outputs.image-name }}
          container-name: ${{ inputs.containerName }}
          containerPort: ${{ inputs.containerPort }}
          targetGroupArn: ${{ env.targetGroupArn }}
          securityGroups: ${{ env.securityGroups }}
          subnets: ${{ env.subnets }}
          task-definition-file: ${{ env.task-definition-file }}
          replace-variables: |
            {{TAG}}= ${{ env.service-tag }}
          wait: true
