on:
  workflow_call:
    inputs:
      service-config-name:
        required: true
        type: string
      containerName:
        required: false
        type: string
      containerPort:
        required: false
        type: string
      ecs-service:
        required: false
        type: string
      deploy-env:
        required: false
        type: string
      repo-name:
        required: false
        type: string
      branch:
        required: false
        type: string
  
jobs:
  ci_build:
    runs-on: [ self-hosted ]
    environment:
      name: ${{ inputs.deploy-env }}
    env:
      deploy_env: ${{ inputs.deploy-env }}
    outputs:
      image-name: ${{ steps.output.outputs.image-name }}
    name: CI flow
    steps:
      - name: Get code
        uses: liberty-group-tech/cicd-actions/.github/actions/get-code@master
        with:
          repo-name: ${{ inputs.repo-name }}
          token: ${{ secrets.REPO_T }}
          branch: ${{ inputs.branch }}
      - name: Transfer env to lowercase
        run: |
          echo "deploy_env_lowercase=${deploy_env,,}" >>${GITHUB_ENV}
      - name: Init Config
        uses: liberty-group-tech/cicd-actions/.github/actions/get-prod-config@master
        with:
          service-config-name: ${{ inputs.service-config-name }}
          token: ${{ secrets.REPO_T }}
          config-file: env-config-prod-service.yml
          deploy-env: ${{ env.deploy_env_lowercase }}
          deploy-sub-env: prod
      - name: Do health check
        uses: liberty-group-tech/cicd-actions/.github/actions/health-check@master
        with:
          env_not_ready: ${{ env.env_not_ready }}
          deploy_env_lowercase: ${{ env.deploy_env_lowercase }}
      - name: Docker build and push
        id: docker-build
        uses: liberty-group-tech/cicd-actions/.github/actions/ecr-build-push@master
        with:
          aws-region: ${{ env.aws-region }}
          aws-tools-region: ${{ env.aws-tools-region }}
          aws-role: ${{ env.aws-role }}
          project-name: ${{ inputs.containerName }}
          aws-registry: ${{ env.aws-registry }}
          need-del-local-image: true
          env-commit-sha: ${{ env.env-commit-sha }}
      - run: echo ${{ steps.docker-build.outputs.image-name }}
        shell: bash
      - name: Set out put
        id: output
        run: |
          echo "image-name=${{ steps.docker-build.outputs.image-name }}" >> $GITHUB_OUTPUT    
  prod_deploy:
    name: Prod Deploy
    if: ${{ !failure() && !cancelled() }}
    uses: liberty-group-tech/cicd-flows/.github/workflows/prod-cd.yml@master
    secrets: inherit
    needs: [ci_build]
    with:
      service-config-name: ${{ inputs.service-config-name }}
      deploy-env: ${{ inputs.deploy_env }}
      deploy_tag: normal
      image-name: ${{ needs.ci_build.outputs.image-name }}
      deploy_sub_env: prod
      containerPort: ${{ inputs.containerPort }}