on:
  workflow_call:
    inputs:
      service-config-name:
        required: true
        type: string
      jar-path:
        required: true
        type: string
      java-version:
        required: false
        type: number
      containerName:
        required: false
        type: string
      containerPort:
        required: false
        type: string
      ecs-service:
        required: false
        type: string
      deploy-env:
        required: false
        type: string
      deploy_tag:
        required: false
        type: string
      repo-name:
        required: false
        type: string
      branch:
        required: false
        type: string
      skip-gray:
        required: false
        type: boolean
        default: false
      skip-blue:
        required: false
        type: boolean
        default: false
jobs:
  ci_build:
    runs-on: [ self-hosted, dev-qa-ci ]
    environment:
      name: ${{ inputs.deploy-env }}
    env:
      service-tag: ${{ inputs.deploy_tag }}
      deploy_env: ${{ inputs.deploy-env }}
    name: CI flow
    outputs:
      image-name: ${{ steps.output.outputs.image-name }}
    steps:
      - name: Get code
        uses: liberty-group-tech/cicd-actions/.github/actions/get-code@master
        with:
          repo-name: ${{ inputs.repo-name }}
          token: ${{ secrets.REPO_T }}
          branch: ${{ inputs.branch }}
      - name: Transfer env to lowercase
        run: |
          echo "deploy_env_lowercase=${deploy_env,,}" >>${GITHUB_ENV}
      - name: Init Config
        uses: liberty-group-tech/cicd-actions/.github/actions/get-config@master
        with:
          service-config-name: ${{ inputs.service-config-name }}
          token: ${{ secrets.REPO_T }}
          config-file: env-config-service.yml
          deploy-env: ${{ env.deploy_env_lowercase }}
      - name: Do health check
        uses: liberty-group-tech/cicd-actions/.github/actions/health-check@master
        with:
          env_not_ready: ${{ env.env_not_ready }}
      - name: Code CI build
        uses: liberty-group-tech/cicd-actions/.github/actions/ci-java-gradle-action@master
        with:
          java-version: ${{ inputs.java-version }}
          jar-path: ${{ inputs.jar-path }}
      - name: Docker build and push
        id: docker-build
        uses: liberty-group-tech/cicd-actions/.github/actions/ecr-build-push@master
        with:
          aws-region: ${{ env.aws-region }}
          aws-role: ${{ env.aws-role }}
          project-name: ${{ inputs.containerName }}
          aws-registry: ${{ env.aws-registry }}
          need-del-local-image: true
          env-commit-sha: ${{ env.env-commit-sha }}
      - name: Set out put
        id: output
        run: |
          echo "image-name=${{ steps.docker-build.outputs.image-name }}" >> $GITHUB_OUTPUT
  gray_deploy:
    uses: liberty-group-tech/cicd-flows/.github/workflows/prod-cd.yml@master
    if: ${{ inputs.skip-gray == 'false' }}
    secrets: inherit
    needs: ci_build
    with:
      service-config-name: ${{ inputs.service-config-name }}
      deploy-env: ${{ inputs.deploy_env }}
      deploy_tag: gray
      image-name: ${{ needs.ci_build.outputs.image-name }}
      deploy_sub_env: gray
  blue_deploy:
    uses: liberty-group-tech/cicd-flows/.github/workflows/prod-cd.yml@master
    if: ${{ inputs.skip-blue == 'false' }}
    secrets: gray_deploy
    needs: ci_build
    with:
      service-config-name: ${{ inputs.service-config-name }}
      deploy-env: ${{ inputs.deploy_env }}
      deploy_tag: blue
      image-name: ${{ needs.ci_build.outputs.image-name }}
      deploy_sub_env: blue
  prod_deploy:
    uses: liberty-group-tech/cicd-flows/.github/workflows/prod-cd.yml@master
    secrets: inherit
    needs: blue_deploy
    with:
      service-config-name: ${{ inputs.service-config-name }}
      deploy-env: ${{ inputs.deploy_env }}
      deploy_tag: normal
      image-name: ${{ needs.ci_build.outputs.image-name }}
      deploy_sub_env: prod
