on:
  workflow_call:
    inputs:
      project-folder:
        required: true
        type: string
      node-version:
        required: true
        type: number
      deploy-env:
        required: false
        type: string
jobs:
  ci:
    runs-on: self-hosted
    environment:
      name: ${{ inputs.deploy-env }}
    env:
      s3-url: ${{ secrets.S3_URL }}
      root-url: ${{ secrets.ROOT_URL }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-role: ${{ secrets.AWS_ROLE }}
    name: CICD flow of node build
    steps:
      - name: Code CI build
        uses: PROTOTYPE/cicd-actions/.github/actions/node-ci-action@v1
        with:
          node-version: ${{ inputs.node-version }}
      - name: Assume new role
        uses: PROTOTYPE/cicd-actions/.github/actions/change-aws-role@master
        with:
          aws-region: ${{ env.aws-region }}
          aws-role: ${{ env.aws-role }}
      - name: Push to S3
        uses: PROTOTYPE/cicd-actions/.github/actions/s3-upload@v1
        with:
          filePath: ${{ github.workspace }}/${{ inputs.project-folder }}/
          s3-url: ${{ env.s3-url }}
          s3-prefix: /
          packageKey: /
          rootUrl: ${{ env.root-url }}
