on:
  workflow_call:
    inputs:
      project-folder:
        required: true
        type: string
      node-version:
        required: true
        type: number
      deploy-env:
        required: false
        type: string
jobs:
  ci:
    runs-on: self-hosted
    environment:
      name: ${{ inputs.deploy-env }}
    env:
      s3-url: ${{ secrets.S3_URL }}
    name: CICD flow of node build
    steps:
      - name: Code CI build
        uses: PROTOTYPE/cicd-actions/.github/actions/node-ci-action@master
        with:
          node-version: ${{ inputs.node-version }}
