on:
  workflow_dispatch:
    #inputs:
    #  config-path:
    #    required: true
    #    type: string
    #secrets:
    #  envPAT:
    #    required: true

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: PROTOTYPE/cicd-actions/.github/actions/demo-action@v1
        with:
          who-to-greet: ${{ github.GITHUB_WORKSPACE }}/$(date +'%Y%m%dT%H%M%S')
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
