on:
  workflow_call:
    inputs:
      containerName:
        required: false
        type: string
      containerPort:
        required: false
        type: string
      ecs-service:
        required: false
        type: string
      deploy-env:
        required: false
        type: string
  
jobs:
  ci_build:
    runs-on: self-hosted
    environment:
      name: ${{ inputs.deploy-env }}
    env:
      aws-region: ${{ secrets.AWS_REGION }}
      cluster: ${{ secrets.ECS_CLUSTER }}
      targetGroupArn: ${{ secrets.TARGETGROUPARN }}
      securityGroups: ${{ secrets.SECURITYGROUPS }}
      subnets: ${{ secrets.SUBNETS }}
    name: CI flow of java gradle build
    steps:
      - uses: actions/checkout@v3
      - name: Docker build and push
        id: docker-build
        uses: PROTOTYPE/cicd-actions/.github/actions/ecr-build-push@v1
        with:
          aws-region: ${{ env.aws-region }}
          project-name: ${{ inputs.containerName }}
      - run: echo ${{ steps.docker-build.outputs.image-name }}
        shell: bash
