on:
  workflow_call:
    inputs:
      containerName:
        required: false
        type: string
      containerPort:
        required: false
        type: string
      ecs-service:
        required: false
        type: string
      deploy-env:
        required: false
        type: string
  
jobs:
  ci_build:
    runs-on: self-hosted
    environment:
      name: ${{ inputs.deploy-env }}
    env:
      aws-region: ${{ secrets.AWS_REGION }}
      aws-role: ${{ secrets.AWS_ROLE }}
      cluster: ${{ secrets.ECS_CLUSTER }}
      targetGroupArn: ${{ secrets.TARGETGROUPARN }}
      securityGroups: ${{ secrets.SECURITYGROUPS }}
      subnets: ${{ secrets.SUBNETS }}
      task-definition-file: ${{ secrets.TASK_DEF_FILE }}
    name: CICD flow of Web
    steps:
      - uses: actions/checkout@v3
      - name: Docker build and push
        id: docker-build
        uses: PROTOTYPE/cicd-actions/.github/actions/ecr-build-push@v1
        with:
          aws-region: ${{ env.aws-region }}
          aws-role: ${{ env.aws-role }}
          project-name: ${{ inputs.containerName }}
      - run: echo ${{ steps.docker-build.outputs.image-name }}
        shell: bash
      - name: Deploy Amazon ECS task definition
        uses: PROTOTYPE/cicd-actions/.github/actions/ecs-deploy@v1
        with:
          aws-region: ${{ env.aws-region }}
          aws-role: ${{ env.aws-role }}
          ecs-service: ${{ inputs.ecs-service }}
          ecs-cluster: ${{ env.cluster }}
          image-full-name: ${{ steps.docker-build.outputs.image-name }}
          container-name: ${{ inputs.containerName }}
          containerPort: ${{ inputs.containerPort }}
          targetGroupArn: ${{ env.targetGroupArn }}
          securityGroups: ${{ env.securityGroups }}
          subnets: ${{ env.subnets }}
          wait: true
